url: http://fkpwolf.net
name: 'Fan&#039;s blog'
title: 'Fan&#039;s blog'
description: '执迷不悟'
twitter_username: 'yanchanglu'
github_username: 'fkpwolf'
email: 'fkpwolf at gmail.com'
paginate: 20
markdown: kramdown
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-coffeescript
  - jekyll-paginate
