url: http://fkpwolf.net
name: 'Kunpeng Fan&#039;s Blog'
title: 'Kunpeng Fan&#039;s Blog'
description: '执迷不悟'
twitter_username: 'yanchanglu'
github_username: 'fkpwolf'
email: 'fkpwolf at gmail.com'
paginate: 20
markdown: kramdown
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
theme: minima
minima:
  skin: auto
gems:
  - jekyll-coffeescript
  - jekyll-paginate
